// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: pkg/proto/like.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Like struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LikeIdentifier string `protobuf:"bytes,3,opt,name=like_identifier,json=likeIdentifier,proto3" json:"like_identifier,omitempty"`
	LikedId        int32  `protobuf:"varint,4,opt,name=liked_id,json=likedId,proto3" json:"liked_id,omitempty"`
	CreatedAt      string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Like) Reset() {
	*x = Like{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *Like) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Like) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Like) GetLikeIdentifier() string {
	if x != nil {
		return x.LikeIdentifier
	}
	return ""
}

func (x *Like) GetLikedId() int32 {
	if x != nil {
		return x.LikedId
	}
	return 0
}

func (x *Like) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLikedTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId        int32  `protobuf:"varint,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	LikeIdentifier string `protobuf:"bytes,3,opt,name=like_identifier,json=likeIdentifier,proto3" json:"like_identifier,omitempty"`
}

func (x *GetLikedTweetRequest) Reset() {
	*x = GetLikedTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikedTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedTweetRequest) ProtoMessage() {}

func (x *GetLikedTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedTweetRequest.ProtoReflect.Descriptor instead.
func (*GetLikedTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *GetLikedTweetRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikedTweetRequest) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *GetLikedTweetRequest) GetLikeIdentifier() string {
	if x != nil {
		return x.LikeIdentifier
	}
	return ""
}

type GetLikedTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Likes   []*Like `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikedTweetResponse) Reset() {
	*x = GetLikedTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikedTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedTweetResponse) ProtoMessage() {}

func (x *GetLikedTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedTweetResponse.ProtoReflect.Descriptor instead.
func (*GetLikedTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *GetLikedTweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLikedTweetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLikedTweetResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

type CreateLikeTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId int32 `protobuf:"varint,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *CreateLikeTweetRequest) Reset() {
	*x = CreateLikeTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeTweetRequest) ProtoMessage() {}

func (x *CreateLikeTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLikeTweetRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLikeTweetRequest) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

type CreateLikeTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Like    *Like  `protobuf:"bytes,3,opt,name=like,proto3" json:"like,omitempty"`
}

func (x *CreateLikeTweetResponse) Reset() {
	*x = CreateLikeTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeTweetResponse) ProtoMessage() {}

func (x *CreateLikeTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeTweetResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLikeTweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLikeTweetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateLikeTweetResponse) GetLike() *Like {
	if x != nil {
		return x.Like
	}
	return nil
}

type DeleteLikeTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId int32 `protobuf:"varint,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *DeleteLikeTweetRequest) Reset() {
	*x = DeleteLikeTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeTweetRequest) ProtoMessage() {}

func (x *DeleteLikeTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeTweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteLikeTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLikeTweetRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteLikeTweetRequest) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

type DeleteLikeTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteLikeTweetResponse) Reset() {
	*x = DeleteLikeTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeTweetResponse) ProtoMessage() {}

func (x *DeleteLikeTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeTweetResponse.ProtoReflect.Descriptor instead.
func (*DeleteLikeTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLikeTweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteLikeTweetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLikesTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId     int32 `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	UserIdToGet int32 `protobuf:"varint,2,opt,name=user_id_to_get,json=userIdToGet,proto3" json:"user_id_to_get,omitempty"`
}

func (x *GetLikesTweetRequest) Reset() {
	*x = GetLikesTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikesTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesTweetRequest) ProtoMessage() {}

func (x *GetLikesTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesTweetRequest.ProtoReflect.Descriptor instead.
func (*GetLikesTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{7}
}

func (x *GetLikesTweetRequest) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *GetLikesTweetRequest) GetUserIdToGet() int32 {
	if x != nil {
		return x.UserIdToGet
	}
	return 0
}

type GetLikesTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Likes   []*Like `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikesTweetResponse) Reset() {
	*x = GetLikesTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikesTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesTweetResponse) ProtoMessage() {}

func (x *GetLikesTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesTweetResponse.ProtoReflect.Descriptor instead.
func (*GetLikesTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{8}
}

func (x *GetLikesTweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLikesTweetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLikesTweetResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

type CreateLikeCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId int32 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *CreateLikeCommentRequest) Reset() {
	*x = CreateLikeCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeCommentRequest) ProtoMessage() {}

func (x *CreateLikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLikeCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLikeCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type CreateLikeCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Like    *Like  `protobuf:"bytes,3,opt,name=like,proto3" json:"like,omitempty"`
}

func (x *CreateLikeCommentResponse) Reset() {
	*x = CreateLikeCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeCommentResponse) ProtoMessage() {}

func (x *CreateLikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLikeCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLikeCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateLikeCommentResponse) GetLike() *Like {
	if x != nil {
		return x.Like
	}
	return nil
}

type DeleteLikeCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId int32 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *DeleteLikeCommentRequest) Reset() {
	*x = DeleteLikeCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeCommentRequest) ProtoMessage() {}

func (x *DeleteLikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteLikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteLikeCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteLikeCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteLikeCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteLikeCommentResponse) Reset() {
	*x = DeleteLikeCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLikeCommentResponse) ProtoMessage() {}

func (x *DeleteLikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLikeCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteLikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLikeCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteLikeCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLikesCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId int32 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *GetLikesCommentRequest) Reset() {
	*x = GetLikesCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikesCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesCommentRequest) ProtoMessage() {}

func (x *GetLikesCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesCommentRequest.ProtoReflect.Descriptor instead.
func (*GetLikesCommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{13}
}

func (x *GetLikesCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetLikesCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Likes   []*Like `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikesCommentResponse) Reset() {
	*x = GetLikesCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikesCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesCommentResponse) ProtoMessage() {}

func (x *GetLikesCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesCommentResponse.ProtoReflect.Descriptor instead.
func (*GetLikesCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{14}
}

func (x *GetLikesCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLikesCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLikesCommentResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

type GetLikeTweetByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetLikeTweetByUserRequest) Reset() {
	*x = GetLikeTweetByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeTweetByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeTweetByUserRequest) ProtoMessage() {}

func (x *GetLikeTweetByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeTweetByUserRequest.ProtoReflect.Descriptor instead.
func (*GetLikeTweetByUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{15}
}

func (x *GetLikeTweetByUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLikeTweetByUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Likes   []*Like `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikeTweetByUserResponse) Reset() {
	*x = GetLikeTweetByUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeTweetByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeTweetByUserResponse) ProtoMessage() {}

func (x *GetLikeTweetByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeTweetByUserResponse.ProtoReflect.Descriptor instead.
func (*GetLikeTweetByUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{16}
}

func (x *GetLikeTweetByUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLikeTweetByUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLikeTweetByUserResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

type GetLikeCommentByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetLikeCommentByUserRequest) Reset() {
	*x = GetLikeCommentByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeCommentByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCommentByUserRequest) ProtoMessage() {}

func (x *GetLikeCommentByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCommentByUserRequest.ProtoReflect.Descriptor instead.
func (*GetLikeCommentByUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{17}
}

func (x *GetLikeCommentByUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLikeCommentByUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Likes   []*Like `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetLikeCommentByUserResponse) Reset() {
	*x = GetLikeCommentByUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_like_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLikeCommentByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeCommentByUserResponse) ProtoMessage() {}

func (x *GetLikeCommentByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_like_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeCommentByUserResponse.ProtoReflect.Descriptor instead.
func (*GetLikeCommentByUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_like_proto_rawDescGZIP(), []int{18}
}

func (x *GetLikeCommentByUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLikeCommentByUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLikeCommentByUserResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

var File_pkg_proto_like_proto protoreflect.FileDescriptor

var file_pkg_proto_like_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6b, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x69, 0x6b, 0x65,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6c, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x73, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x69, 0x6b, 0x65, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x6c, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x22, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c,
	0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x04, 0x6c, 0x69,
	0x6b, 0x65, 0x22, 0x4c, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x4d, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x56, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x22, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x22, 0x52, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x6b,
	0x65, 0x22, 0x52, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x6a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x6d, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73,
	0x22, 0x36, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x6f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x05,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69,
	0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x32, 0xad, 0x05, 0x0a, 0x0b, 0x4c, 0x69,
	0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b,
	0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_like_proto_rawDescOnce sync.Once
	file_pkg_proto_like_proto_rawDescData = file_pkg_proto_like_proto_rawDesc
)

func file_pkg_proto_like_proto_rawDescGZIP() []byte {
	file_pkg_proto_like_proto_rawDescOnce.Do(func() {
		file_pkg_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_like_proto_rawDescData)
	})
	return file_pkg_proto_like_proto_rawDescData
}

var file_pkg_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_proto_like_proto_goTypes = []any{
	(*Like)(nil),                         // 0: Like
	(*GetLikedTweetRequest)(nil),         // 1: GetLikedTweetRequest
	(*GetLikedTweetResponse)(nil),        // 2: GetLikedTweetResponse
	(*CreateLikeTweetRequest)(nil),       // 3: CreateLikeTweetRequest
	(*CreateLikeTweetResponse)(nil),      // 4: CreateLikeTweetResponse
	(*DeleteLikeTweetRequest)(nil),       // 5: DeleteLikeTweetRequest
	(*DeleteLikeTweetResponse)(nil),      // 6: DeleteLikeTweetResponse
	(*GetLikesTweetRequest)(nil),         // 7: GetLikesTweetRequest
	(*GetLikesTweetResponse)(nil),        // 8: GetLikesTweetResponse
	(*CreateLikeCommentRequest)(nil),     // 9: CreateLikeCommentRequest
	(*CreateLikeCommentResponse)(nil),    // 10: CreateLikeCommentResponse
	(*DeleteLikeCommentRequest)(nil),     // 11: DeleteLikeCommentRequest
	(*DeleteLikeCommentResponse)(nil),    // 12: DeleteLikeCommentResponse
	(*GetLikesCommentRequest)(nil),       // 13: GetLikesCommentRequest
	(*GetLikesCommentResponse)(nil),      // 14: GetLikesCommentResponse
	(*GetLikeTweetByUserRequest)(nil),    // 15: GetLikeTweetByUserRequest
	(*GetLikeTweetByUserResponse)(nil),   // 16: GetLikeTweetByUserResponse
	(*GetLikeCommentByUserRequest)(nil),  // 17: GetLikeCommentByUserRequest
	(*GetLikeCommentByUserResponse)(nil), // 18: GetLikeCommentByUserResponse
}
var file_pkg_proto_like_proto_depIdxs = []int32{
	0,  // 0: GetLikedTweetResponse.likes:type_name -> Like
	0,  // 1: CreateLikeTweetResponse.like:type_name -> Like
	0,  // 2: GetLikesTweetResponse.likes:type_name -> Like
	0,  // 3: CreateLikeCommentResponse.like:type_name -> Like
	0,  // 4: GetLikesCommentResponse.likes:type_name -> Like
	0,  // 5: GetLikeTweetByUserResponse.likes:type_name -> Like
	0,  // 6: GetLikeCommentByUserResponse.likes:type_name -> Like
	3,  // 7: LikeService.CreateLikeTweet:input_type -> CreateLikeTweetRequest
	5,  // 8: LikeService.DeleteLikeTweet:input_type -> DeleteLikeTweetRequest
	7,  // 9: LikeService.GetLikesTweet:input_type -> GetLikesTweetRequest
	15, // 10: LikeService.GetLikeTweetByUser:input_type -> GetLikeTweetByUserRequest
	1,  // 11: LikeService.GetLikedTweet:input_type -> GetLikedTweetRequest
	9,  // 12: LikeService.CreateLikeComment:input_type -> CreateLikeCommentRequest
	11, // 13: LikeService.DeleteLikeComment:input_type -> DeleteLikeCommentRequest
	13, // 14: LikeService.GetLikesComment:input_type -> GetLikesCommentRequest
	17, // 15: LikeService.GetLikeCommentByUser:input_type -> GetLikeCommentByUserRequest
	4,  // 16: LikeService.CreateLikeTweet:output_type -> CreateLikeTweetResponse
	6,  // 17: LikeService.DeleteLikeTweet:output_type -> DeleteLikeTweetResponse
	8,  // 18: LikeService.GetLikesTweet:output_type -> GetLikesTweetResponse
	16, // 19: LikeService.GetLikeTweetByUser:output_type -> GetLikeTweetByUserResponse
	2,  // 20: LikeService.GetLikedTweet:output_type -> GetLikedTweetResponse
	10, // 21: LikeService.CreateLikeComment:output_type -> CreateLikeCommentResponse
	12, // 22: LikeService.DeleteLikeComment:output_type -> DeleteLikeCommentResponse
	14, // 23: LikeService.GetLikesComment:output_type -> GetLikesCommentResponse
	18, // 24: LikeService.GetLikeCommentByUser:output_type -> GetLikeCommentByUserResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_like_proto_init() }
func file_pkg_proto_like_proto_init() {
	if File_pkg_proto_like_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_like_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Like); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikedTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikedTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLikeTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLikeTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLikeTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLikeTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikesTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikesTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLikeCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLikeCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLikeCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLikeCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikesCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikesCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikeTweetByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikeTweetByUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikeCommentByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_like_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetLikeCommentByUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_like_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_like_proto_goTypes,
		DependencyIndexes: file_pkg_proto_like_proto_depIdxs,
		MessageInfos:      file_pkg_proto_like_proto_msgTypes,
	}.Build()
	File_pkg_proto_like_proto = out.File
	file_pkg_proto_like_proto_rawDesc = nil
	file_pkg_proto_like_proto_goTypes = nil
	file_pkg_proto_like_proto_depIdxs = nil
}
